logging:
  level:
    io.mustelidae.riverotter: info
    org.springframework.boot.actuate: off
    org.springframework.web: debug
    org.springframework.boot: info
    org.hibernate.SQL: debug
    org.hibernate.tool.schema: error
    com.zaxxer.hikari: error
    io.swagger.models.parameters.AbstractSerializableParameter: error

server:
  error:
    include-stacktrace: always
    whitelabel:
      enabled: false
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  port: 6400

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27018
      database: riverOtter
  mvc:
    log-request-details: true

springdoc:
  show-actuator: false
  swagger-ui:
    enabled: true
    tags-sorter: alpha

app:
  available-countries: KR,US
  country:
    korea:
      saturday-is-holiday: true
  client:
    government:
      use-dummy: true
      host: http://apis.data.go.kr
      key: lpQXHxRKaKapgLrvvnx9%2BuZHMW4xD8Nm%2Fnr1Nr9My%2F4V9g7tJe1yikoJyLq1KpzgQXA1dNir5XTVNRsbdp6KSg%3D%3D
      timeout: 6000
    abstract:
      use-dummy: true
      host: https://holidays.abstractapi.com
      key: b7814953c3474896aae378fada8cd409
      timeout: 6000
